### DISCUSSION TITLE
blog/setup-jellyfin-with-hardware-acceleration-on-orange-pi-5-rockchip-rk3558/

### DISCUSSION THREAD

**Discussion by giscus** [AkashRajpurohit/AkashRajpurohit#39] [Comments]
# blog/setup-jellyfin-with-hardware-acceleration-on-orange-pi-5-rockchip-rk3558/

Recently I moved my Jellyfin to an Orange Pi 5 Plus server. The Orange Pi 5 has a Rockchip RK3558 SoC with integrated ARM Mali-G610. This guide will show you how to set up Jellyfin with hardware acceleration on the Orange Pi 5.

https://akashrajpurohit.com/blog/setup-jellyfin-with-hardware-acceleration-on-orange-pi-5-rockchip-rk3558/

**Comment by benjaminstart** [comment]
Thank you so much for this!

**Reply by AkashRajpurohit** [reply]
Glad you found it helpful!

**Reply by benjaminstart** [reply]
I am struggling with this. Can you make a ready-to-go image for the Orange Pi 5 Plus that has Jellyfin all setup?

**Reply by AkashRajpurohit** [reply]
If you use the ubuntu-rockchip from Joshua, the 24.04 latest kernel images have the libmali already installed.
So you can just simply skip to the docker setup and it should work out of the box.

**Reply by benjaminstart** [reply]
Thank you. I followed your steps before and I struggled with the docker compose part. Can you please tell me how to enter that? I tried with Portainer but could not get it to work with the 44 video group.

**Reply by AkashRajpurohit** [reply]
So 44 was the group id of the "video" group, it may be different for you, so in the blog I have also mentioned the steps to find the group id on your system.

**Reply by defencedog** [reply]
@akash _If you use the ubuntu-rockchip from Joshua, the 24.04 latest kernel images have the libmali already installed.
So you can just simply skip to the docker setup and it should work out of the box._ I have PanfrostG52 installed on my Opi3b & I can get output
```
--device /dev/dri
--device /dev/dma_heap
--device /dev/rga
--device /dev/mpp_service
```

but cannot get `--device /dev/mali0`

**Reply by AkashRajpurohit** [reply]
@defencedog this means that you don't have libmali present, I haven't tested it for PanfrostG52 with OPI3B, but what you would want to check is how to get the mali drivers for your system.
First, you can also check if OPI3B even supports it.

**Comment by DummyTitan** [comment]
hello,

i followed the instructions religiously, and i got this error,

Failed creating base context during opening of kernel driver.
Kernel module may not have been loaded

and

 Failed creating base context during opening of kernel driver.
Kernel module may not have been loaded

**Reply by AkashRajpurohit** [reply]
What's the base OS that you are running?
Also did you install libmali? I remember seeing some similar errors in past and re-installing libmali fixed it.

**Reply by DummyTitan** [reply]
I used debian since I'm trying to make a nas with omv. When I attempted it with Ubuntu just in case it worked, but not with debian. I am reattempting, this time I'm 80% sure it was the ppa. I downloaded the files and installed them manually at first, but installed them like you did in Ubuntu. I verified and discover you could do the same in debian so I installed the ppa there and am in the process now of verification.

**Reply by DummyTitan** [reply]
now it prints like yours

Splitting the commandline.
Reading option '-v' ... matched as option 'v' (set logging level) with argument'debug'.
Reading option '-init_hw_device' ... matched as option 'init_hw_device' (initialise hardware device) with argument 'rkmpp=rk'.
Reading option '-init_hw_device' ... matched as option 'init_hw_device' (initialise hardware device) with argument 'opencl=ocl@rk'.
Finished splitting the commandline.
Parsing a group of options: global .
Applying option v (set logging level) with argument debug.
Applying option init_hw_device (initialise hardware device) with argument rkmpp=rk.
Applying option init_hw_device (initialise hardware device) with argument opencl=ocl@rk.
arm_release_ver: g13p0-01eac0, rk_so_ver: 10
[AVHWDeviceContext @ 0x55b5c0af00] 1 OpenCL platforms found.
[AVHWDeviceContext @ 0x55b5c0af00] 1 OpenCL devices found on platform "ARM Platform".
[AVHWDeviceContext @ 0x55b5c0af00] 0.0: ARM Platform / Mali-G610 r0p0
[AVHWDeviceContext @ 0x55b5c0af00] cl_arm_import_memory found as platform extension.
[AVHWDeviceContext @ 0x55b5c0af00] cl_khr_image2d_from_buffer found as platform extension.
[AVHWDeviceContext @ 0x55b5c0af00] DRM to OpenCL mapping on ARM function found (clImportMemoryARM).
Successfully parsed a group of options.
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'

**Reply by DummyTitan** [reply]
but i cant seem to make the transcoding work still

**Reply by AkashRajpurohit** [reply]
The libmali seems to be loaded correctly, have you updated the Jellyfin settings to enable hardware acceleration?

**Comment by s0rau** [comment]
libmali is installed on the docker image (see source code)
https://github.com/jellyfin/jellyfin-packaging/blob/master/docker/Dockerfile#L177

Is that still needed to install it on the host too ?

**Reply by AkashRajpurohit** [reply]
I believe yes, since not having it installed did not work for me when I last tested it.
You can give it a shot without installing it and if it works then great, let me know if you end up testing it with installing the libmali explicitly?

**Reply by s0rau** [reply]
At the moment I don't have installed it on host.

Some videos can't be loaded :

```
[hevc_rkmpp @ 0xaaab1872a1a0] Failed to init MPP context: -1
Stream mapping:
  Stream #0:0 -> #0:0 (hevc (hevc_rkmpp) -> h264 (libx264))
  Stream #0:1 -> #0:1 (aac (native) -> aac (libfdk_aac))
Error while opening decoder for input stream #0:0 : Generic error in an external library
```

So I've to disable hardware acceleration.

**Reply by s0rau** [reply]
```
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Europe/London
    security_opt:
      - systempaths=unconfined
      - apparmor=unconfined
    user: 1000:100
    volumes:
      - /data/jf/jellyfin:/config
      - /data/media:/data/media
    devices:
      - /dev/dri:/dev/dri
      - /dev/dma_heap:/dev/dma_heap
      - /dev/mali0:/dev/mali0
      - /dev/rga:/dev/rga
      - /dev/mpp_service:/dev/mpp_service
    ports:
      - 127.0.0.1:8096:8096
    restart: unless-stopped

```


```
 docker exec -it jellyfin /usr/lib/jellyfin-ffmpeg/ffmpeg -v debug -init_hw_device rkmpp=rk -init_hw_device opencl=ocl@rk
ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libxml2 --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=arm64 --cross-prefix=/usr/bin/aarch64-linux-gnu- --toolchain=hardened --enable-cross-compile --enable-rkmpp --enable-rkrga
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
Splitting the commandline.
Reading option '-v' ... matched as option 'v' (set logging level) with argument 'debug'.
Reading option '-init_hw_device' ... matched as option 'init_hw_device' (initialise hardware device) with argument 'rkmpp=rk'.
Reading option '-init_hw_device' ... matched as option 'init_hw_device' (initialise hardware device) with argument 'opencl=ocl@rk'.
Finished splitting the commandline.
Parsing a group of options: global .
Applying option v (set logging level) with argument debug.
Applying option init_hw_device (initialise hardware device) with argument rkmpp=rk.
Applying option init_hw_device (initialise hardware device) with argument opencl=ocl@rk.
arm_release_ver: g13p0-01eac0, rk_so_ver: 10
Failed creating base context during opening of kernel driver.
Kernel module may not have been loaded
[AVHWDeviceContext @ 0xaaaaf7834f00] 1 OpenCL platforms found.
[AVHWDeviceContext @ 0xaaaaf7834f00] 1 OpenCL devices found on platform "ARM Platform".
arm_release_ver: g13p0-01eac0, rk_so_ver: 10
Failed creating base context during opening of kernel driver.
Kernel module may not have been loaded
[AVHWDeviceContext @ 0xaaaaf7834f00] 0.0: ARM Platform / Unknown Device
```

**Reply by s0rau** [reply]
I've also add /etc/udev/rules.d/99-rk-device-permissions.rules for kernel (see https://jellyfin.org/docs/general/administration/hardware-acceleration/rockchip/#debian-and-ubuntu-linux)

My user is in groups : `render` and `video`

In addition : I'm not a "fan" of wget some .deb package in the host, in order to installed it on a production server.
We can't update it by `apt upgrade` and that package may stay orphan.

**Reply by s0rau** [reply]
Here's some news : 
https://www.reddit.com/r/SBCs/comments/1fbjoea/armbian_images_with_panthor_opengl_es_31_gpu/

**Reply by s0rau** [reply]
```
cp /lib/firmware/arm/mali/arch10.8/mali_csffw.bin /lib/firmware

 docker exec -it jellyfin /usr/lib/jellyfin-ffmpeg/ffmpeg -v debug -init_hw_device rkmpp=rk -init_hw_device opencl=ocl@rk
ffmpeg version 6.0.1-Jellyfin Copyright (c) 2000-2023 the FFmpeg developers
  built with gcc 12 (Debian 12.2.0-14)
  configuration: --prefix=/usr/lib/jellyfin-ffmpeg --target-os=linux --extra-version=Jellyfin --disable-doc --disable-ffplay --disable-ptx-compression --disable-static --disable-libxcb --disable-sdl2 --disable-xlib --enable-lto --enable-gpl --enable-version3 --enable-shared --enable-gmp --enable-gnutls --enable-chromaprint --enable-opencl --enable-libdrm --enable-libxml2 --enable-libass --enable-libfreetype --enable-libfribidi --enable-libfontconfig --enable-libbluray --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libopenmpt --enable-libdav1d --enable-libsvtav1 --enable-libwebp --enable-libvpx --enable-libx264 --enable-libx265 --enable-libzvbi --enable-libzimg --enable-libfdk-aac --arch=arm64 --cross-prefix=/usr/bin/aarch64-linux-gnu- --toolchain=hardened --enable-cross-compile --enable-rkmpp --enable-rkrga
  libavutil      58.  2.100 / 58.  2.100
  libavcodec     60.  3.100 / 60.  3.100
  libavformat    60.  3.100 / 60.  3.100
  libavdevice    60.  1.100 / 60.  1.100
  libavfilter     9.  3.100 /  9.  3.100
  libswscale      7.  1.100 /  7.  1.100
  libswresample   4. 10.100 /  4. 10.100
  libpostproc    57.  1.100 / 57.  1.100
Splitting the commandline.
Reading option '-v' ... matched as option 'v' (set logging level) with argument 'debug'.
Reading option '-init_hw_device' ... matched as option 'init_hw_device' (initialise hardware device) with argument 'rkmpp=rk'.
Reading option '-init_hw_device' ... matched as option 'init_hw_device' (initialise hardware device) with argument 'opencl=ocl@rk'.
Finished splitting the commandline.
Parsing a group of options: global .
Applying option v (set logging level) with argument debug.
Applying option init_hw_device (initialise hardware device) with argument rkmpp=rk.
Applying option init_hw_device (initialise hardware device) with argument opencl=ocl@rk.
arm_release_ver: g13p0-01eac0, rk_so_ver: 10
[AVHWDeviceContext @ 0xaaaac71b4f00] 1 OpenCL platforms found.
[AVHWDeviceContext @ 0xaaaac71b4f00] 1 OpenCL devices found on platform "ARM Platform".
[AVHWDeviceContext @ 0xaaaac71b4f00] 0.0: ARM Platform / Mali-G610 r0p0
[AVHWDeviceContext @ 0xaaaac71b4f00] cl_arm_import_memory found as platform extension.
[AVHWDeviceContext @ 0xaaaac71b4f00] cl_khr_image2d_from_buffer found as platform extension.
[AVHWDeviceContext @ 0xaaaac71b4f00] DRM to OpenCL mapping on ARM function found (clImportMemoryARM).
Successfully parsed a group of options.
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...

Use -h to get full help or, even better, run 'man ffmpeg'


 dmesg|grep Mali
[  367.986293] mali fb000000.gpu: Loading Mali firmware 0x1010000
[  367.988606] mali fb000000.gpu: Mali firmware git_sha: 814b47b551159067b67a37c4e9adda458ad9d852
```

 Seems the firmware not on the right folder see above :

**Reply by s0rau** [reply]
Firmware is correctly loaded !

I've added your settings, nice tricks :+1: 
```
    security_opt: # enables full access to /sys and /proc, still far better than privileged: true
      - systempaths=unconfined
      - apparmor=unconfined
    group_add:
      - 44 # video group

```

**Comment by Daavidaviid** [comment]
Have you tried running a console emulator on it afterward?

**Comment by gilbrotheraway** [comment]
how does it work that you are transcoding from 3mbps file up to 10mbps?

**Reply by gilbrotheraway** [reply]
i'm trying to get a baseline cause i found my RGA usage a bit high(though it depends on source and target encode)

**Comment by jzhou404** [comment]
I just got ERROR on the very first step, help need. THX

The platform is RK3566 based.

root@armbian:~# uname -r
6.1.92-ophub
root@armbian:~# ls -l /dev | grep -E "mpp|rga|dri|dma_heap"
root@armbian:~# sudo add-apt-repository ppa:rockchip-linux/ppa
ERROR: ppa 'rockchip-linux/ppa' not found (use --login if private)

**Comment by patyuen-usa** [comment]
This broke my display. Certain programs like VLC and Timeshift would no longer display in gui. Had to revert the driver with these steps. 

# 🛠️ GPU Recovery Script for Orange Pi 5 Plus (RK3588) on Ubuntu 24.04
# Use this if hardware acceleration broke after installing Rockchip/Jellyfin drivers.

# Save this as: safe-gpu-recover.sh
cat << 'EOF' > safe-gpu-recover.sh
#!/bin/bash

set -e

echo "==== 1. Remove Rockchip GPU packages ===="
sudo apt remove --purge -y rockchip-multimedia-config rockchip-mpp || true
sudo apt autoremove -y

echo "==== 2. Purge manually installed Mali GPU packages ===="
dpkg -l | grep -i mali | awk '{print $2}' | xargs -r sudo dpkg -P || true

echo "==== 3. Cleanup Xorg config if present ===="
if [ -f /etc/X11/xorg.conf ]; then
  sudo mv /etc/X11/xorg.conf /etc/X11/xorg.conf.backup.$(date +%s)
fi

echo "==== 4. Reinstall Mesa and GPU libraries ===="
sudo apt update
sudo apt install --reinstall -y \
  mesa-vulkan-drivers mesa-utils libgl1-mesa-dri \
  libegl1-mesa libgbm1 libdrm2

echo "==== 5. Ensure LightDM is installed and enabled ===="
if ! systemctl is-enabled lightdm &> /dev/null; then
  sudo apt install -y lightdm
  sudo systemctl enable lightdm
  sudo systemctl start lightdm
fi

echo "==== 6. Check Panfrost driver ===="
lsmod | grep panfrost && echo "✅ Panfrost loaded" || echo "❌ Panfrost not loaded"

echo "==== 7. Check DRM nodes ===="
[ -d /dev/dri ] && echo "✅ DRM initialized" || echo "❌ Missing /dev/dri"

echo "==== 8. Check OpenGL renderer ===="
glxinfo | grep -i "OpenGL renderer"

echo ""
read -p "Reboot now? (y/n): " confirm
[[ "$confirm" =~ ^[Yy]$ ]] && sudo reboot
EOF

# ✅ Make executable and run
chmod +x safe-gpu-recover.sh
./safe-gpu-recover.sh

**Comment by VorpalQ** [comment]
Thanks very much for doing this writeup, I now have HW accelerated jellyfin on my Opi5+.

**Reply by AkashRajpurohit** [reply]
You're welcome 😄

**Comment by luciano-buono** [comment]
Hi, thank you for the guide! Very helpful

Could you help me adapting this to a k8s setup?

I have created my deployment and HW decoding is working but ONLY if I set my container to privileged. I would think that setting the fsGroup to 44 should be enough for the app to use the /dev devices but apparently not.

Any ideas what I can be missing?


```yml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    container.apparmor.security.beta.kubernetes.io/jellyfin: unconfined
    reloader.stakater.com/auto: 'true'
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: jellyfin
    app.kubernetes.io/version: 10.10.7
    argocd.argoproj.io/instance: streaming-server
    helm.sh/chart: jellyfin-6.5.0
  name: jellyfin
  namespace: streaming-server
spec:
  revisionHistoryLimit: 5
  selector:
    matchLabels:
      app.kubernetes.io/name: jellyfin
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jellyfin
    spec:
      containers:
        - image: ghcr.io/jellyfin/jellyfin:10.10.7
          imagePullPolicy: IfNotPresent
          name: jellyfin
          ports:
            - containerPort: 8096
              name: http
              protocol: TCP
            - containerPort: 7359
              name: http2
              protocol: UDP
          resources:
            limits:
              cpu: 1
              memory: 2Gi
            requests:
              cpu: 50m
              memory: 128Mi
          securityContext:
            allowPrivilegeEscalation: true
            privileged: true
            readOnlyRootFilesystem: false
            runAsNonRoot: false
            seccompProfile:
              type: Unconfined
          volumeMounts:
            - mountPath: /dev/dri
              name: dev-dri
            - mountPath: /dev/dma_heap
              name: dev-dma-heap
              readOnly: true
            - mountPath: /dev/mali0
              name: dev-mali0
              readOnly: true
            - mountPath: /dev/rga
              name: dev-rga
              readOnly: true
            - mountPath: /dev/mpp_service
              name: dev-mpp-service
              readOnly: true
            - mountPath: /config
              name: jellyfin-config
            - mountPath: /data
              name: torrent-downloads
      securityContext:
        fsGroup: 44
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 0
        runAsNonRoot: false
        runAsUser: 0
        supplementalGroups:
          - 44
      terminationGracePeriodSeconds: null
      volumes:
        - hostPath:
            path: /dev/dma_heap
            type: Directory
          name: dev-dma-heap
        - hostPath:
            path: /dev/dri
            type: Directory
          name: dev-dri
        - hostPath:
            path: /dev/mali0
            type: CharDevice
          name: dev-mali0
        - hostPath:
            path: /dev/mpp_service
            type: CharDevice
          name: dev-mpp-service
        - hostPath:
            path: /dev/rga
            type: CharDevice
          name: dev-rga
        - name: jellyfin-config
          persistentVolumeClaim:
            claimName: jellyfin-config
        - name: torrent-downloads
          persistentVolumeClaim:
            claimName: torrent-downloads

```
